import random

random.random() NUMERO ALEATORIO ENTRE 0 E 1

random.randint(1,5) NUMERO ALEATORIO NA FAIXA ESPECIFICA

random.randrange(0, 10, 2) NUM ALEATORIO COM PASSO

random.choice(x) ESCOLHE ALEATORIO UM ELEMENTO EM UMA LISTA

import time as tm COLOCAR UMA SIGLA/APELIDO PARA A BIBLIOTECA

tm.time() USADO PARA MEDIR O TEMPO DE RUM DE UM CODIGO

tm.sleep() PARA 'ATRASAR' O PROCESSAMENTO

